spring:
  datasource:
    url: jdbc:h2:mem:wymiensiepl
    username: admin
    password: admin
    diver-class-name: org.h2.Driver
    platform:
  jpa:
    hibernate:
      dll-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  servlet:
    context-path: /api/v1
amazon:
  aws:
    access-key: todo
    secret-key: todo
    region: todo
